import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

'''
Relevant survey Qs:

'Does your institution host activities connected to astronomy-related instrumentation?'
 'What is the approximate expenditure of your institution in this area over the years 2019-2023?',
 'In your institution, what is the approximate distribution of instrumentation-focused personnel effort (FTE) given to (in percent):',
 'What would the ideal distribution of resources (funding and FTE) across the following areas look like for your institution (in percent)?',
 'Do you believe that overall funding received by your institute for astronomy instrumentation is:',
 'If changes to instrumentation funding could be made, how would you rank the following options in importance (1 being the most important):',
 'In the future, how does your institution expect its capacity in instrumentation-related activities to change?',
 'If you answered "Grow," which areas of growth have been identified (select all that apply)?',
 'If you answered “No change," what factors are inhibiting growth (select all that apply):',
 'If you answered "Reduce,” what factors are driving the reduction in capacity (select all that apply):',
 'What are the main benefits of instrumentation to your institution, the astronomy community, and society (select up to 5)?',
 'How would you rate the current level of collaboration between your research institution and industry partners? Please describe the institutional approach to collaboration and how extensively these collaborations are supported and encouraged at the institutional level',
 'In the past 5 years (2019-2023) have any higher-degree graduates at your institute completed an industry internship during their degree? (details are requested in the excel spreadsheet provided to institute contacts)',
 'What institutional strategies or initiatives do you believe could enhance industry engagement within the astronomy community?',
 'Does your institute have a clear policy and associated training on how to achieve industry engagement for translational research?',
 'Has your institute supported research initiatives involving industry, government, or international research organisations?',
 'Please provide short outline of size of project (years, approximate total cost,# persons) and short outline of nature of the project (e.g. new technology development, adapting commercial products, larger-scale build of existing astronomy-derived instrumentation etc).',
 'Did your institute utilize structured management processes or international standards (e.g. ISO9001) to implement the programs?',
 'Would your group benefit from further advice or training on industry engagement and translational research?',
 'Does your institute engage in research where significant intellectual property (IP) is or was generated by your organisation, or is expected to be generated?',
 "Did the contractual arrangement restrict either party's freedom to access, or otherwise further exploit, the IP?",
 'What were the reasons in your view for the success or failure in generation or transfer of IP?',
 'Was the partner able to commercially exploit the IP that resulted from the project or interaction?'
 'If yes, and if the partner was able to commercially exploit the IP, are you able to give a quantitative estimate of financial benefit or other impact?',
 "How developed do you consider your institute's skills to successfully exploit industry engagement opportunities and grants, commercial opportunities, industry capabilities and IP management?",
 'Do you believe that there is sufficient coordination and effort made within the Australian astronomy community to develop the flow of commercial products into, and IP out of, astronomy?',
 'Would your Institute be happy to be consulted further by NCA Decadal Plan WG3.3 Industry?',
 'Did your institution engage in the Australian Research Council Engagement and Impact Assessment (EIA) in 2018 or 2024 (now postponed)? If Yes do you have any example case studies highlighting fundamental research in astronomy with impact outcomes?',
 'Are you able to provide case summaries for applicable cases? Can we highlight these in the decadal plan?',
'''

stem = '/Users/bandari/Documents/git.repos/decadal/data/'

df = pd.read_csv(stem + 'survey_data.csv')

df = df.drop(0)
df_sorted = df.sort_values('For which Australian Astronomy institution/department are you reporting for?')

# Does your institution host activities connected to astronomy-related instrumentation?
df_subset = df[['For which Australian Astronomy institution/department are you reporting for?','Does your institution host activities connected to astronomy-related instrumentation?']]
institutions = df_subset.iloc[:, 0].tolist()
responses = df_subset.iloc[:, 1].tolist()
# Plotting
plt.clf()
plt.figure(figsize=(5, len(institutions) * 0.5))
for idx, (institution, response) in enumerate(zip(institutions, responses)):
    if response=='Yes':  # If the response is 'Yes'
        plt.plot(1, idx, marker='$Y$', markersize=10, color='g', label='Hosts Instrumentation Activities' if idx == 0 else "")  # Green Y for 'Yes'
    else:
        plt.plot(1, idx, marker='$N$', markersize=10, color='r', label='Does Not Host Instrumentation Activities' if idx == 0 else "")  # Red x for 'No' (or nan)
plt.yticks(range(len(institutions)), institutions)
plt.xticks([])  # Hide x-axis ticks
plt.title('Institutional Participation\nin Astronomy-Related\nInstrumentation Activities')
#plt.legend()
plt.tight_layout()
plt.savefig('junk1.png')

# What is the approximate expenditure of your institution in this area over the years 2019-2023?
df_subset = df[['For which Australian Astronomy institution/department are you reporting for?','What is the approximate expenditure of your institution in this area over the years 2019-2023?']]
institutions = df_subset.iloc[:, 0].tolist()
responses = df_subset.iloc[:, 1].tolist()
# Plotting
plt.figure(figsize=(7, len(institutions) * 0.5))
for idx, (institution, response) in enumerate(zip(institutions, responses)):
    plt.text(0.1, idx-0.1, response, fontsize=12, color='k')
plt.yticks(range(len(institutions)), institutions)
plt.xticks([])  # Hide x-axis ticks
plt.ylim([-0.5, len(institutions)])
plt.title('Institutional Participation\nin Astronomy-Related\nInstrumentation Activities')
#plt.legend()
plt.tight_layout()
plt.savefig('junk2.png')